import { useEffect, useMemo, useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { normalizeAbi, type Abi } from '@semantic-dapp/spec';
import { GeneratedApp } from '@semantic-dapp/renderer';
import { ToastViewport } from '@semantic-dapp/components';
import type { SemanticBundle } from '@semantic-dapp/export';
import { AppProviders } from './wallet/Providers.js';
import { useContractRuntime } from './runtime.js';
import { loadBundle } from './bundle.js';
import { LoadContractPanel } from './LoadContractPanel.js';

const CONTRACT_ID = 'contract';
const FALLBACK_RPC = 'http://127.0.0.1:8545';

/** A usable RPC URL: the bundle's, or a local default so the app never crashes. */
function effectiveRpc(bundle: SemanticBundle): string {
  return bundle.rpcUrl && bundle.rpcUrl.length > 0 ? bundle.rpcUrl : FALLBACK_RPC;
}

/** Inner view: has providers in scope, so it can use wagmi hooks. */
function BundleView({
  bundle,
  isDemo,
  onOpenLoader,
  onRestoreDemo,
}: {
  bundle: SemanticBundle;
  isDemo: boolean;
  onOpenLoader: () => void;
  onRestoreDemo?: () => void;
}) {
  const abi = bundle.abi as Abi;
  const model = useMemo(() => normalizeAbi(abi), [abi]);
  const runtime = useContractRuntime({
    abi,
    chainId: bundle.chainId,
    rpcUrl: effectiveRpc(bundle),
    ...(bundle.address ? { address: bundle.address } : {}),
    ...(bundle.contractName ? { name: bundle.contractName } : {}),
  });

  return (
    <div className="app-shell">
      <header className="app-header">
        <div>
          <h1 className="app-header__title">{bundle.contractName ?? bundle.name}</h1>
          <span className="app-header__sub">
            chain {bundle.chainId}
            {bundle.address ? ` · ${bundle.address}` : ''}
            {isDemo ? ' · demo bundle' : ' · your contract'}
          </span>
        </div>
        <div className="app-header__actions">
          {!isDemo && onRestoreDemo ? (
            <button type="button" className="sd-btn sd-btn--ghost" onClick={onRestoreDemo}>
              Back to demo
            </button>
          ) : null}
          <button type="button" className="sd-btn sd-btn--write" onClick={onOpenLoader}>
            Load your contract
          </button>
          <ConnectButton showBalance={false} chainStatus="icon" accountStatus="address" />
        </div>
      </header>

      <GeneratedApp
        manifest={bundle.manifest}
        model={model}
        runtime={runtime}
        contractId={CONTRACT_ID}
        safety={bundle.address ? {} : undefined}
      />

      <footer className="app-footer">
        Generated by Semantic Dapp · runs entirely in your browser ·{' '}
        <a href="https://github.com/TacitvsXI/semantic-dapp" target="_blank" rel="noreferrer">
          GitHub
        </a>
      </footer>

      <ToastViewport />
    </div>
  );
}

export function App() {
  const [demo, setDemo] = useState<SemanticBundle | null>(null);
  const [bundle, setBundle] = useState<SemanticBundle | null>(null);
  const [isDemo, setIsDemo] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showLoader, setShowLoader] = useState(false);

  useEffect(() => {
    let cancelled = false;
    loadBundle()
      .then((result) => {
        if (cancelled) return;
        setDemo(result.bundle);
        setBundle(result.bundle);
        setIsDemo(result.isDemo);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (error)
    return (
      <div className="app-shell">
        <p className="app-error">{error}</p>
      </div>
    );
  if (!bundle || !demo)
    return (
      <div className="app-shell">
        <p className="app-status">Loading…</p>
      </div>
    );

  return (
    <AppProviders
      key={`${bundle.chainId}:${effectiveRpc(bundle)}`}
      chainId={bundle.chainId}
      rpcUrl={effectiveRpc(bundle)}
      name={bundle.contractName ?? bundle.name}
    >
      <BundleView
        bundle={bundle}
        isDemo={isDemo}
        onOpenLoader={() => setShowLoader(true)}
        {...(!isDemo
          ? {
              onRestoreDemo: () => {
                setBundle(demo);
                setIsDemo(true);
              },
            }
          : {})}
      />
      <LoadContractPanel
        open={showLoader}
        onClose={() => setShowLoader(false)}
        onLoaded={(next) => {
          setBundle(next);
          setIsDemo(false);
        }}
        defaultChainId={bundle.chainId}
        {...(bundle.rpcUrl ? { defaultRpcUrl: bundle.rpcUrl } : {})}
      />
    </AppProviders>
  );
}
