import { useEffect, useMemo, useState } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { normalizeAbi, type Abi } from '@semantic-dapp/spec';
import { GeneratedApp } from '@semantic-dapp/renderer';
import { ToastViewport } from '@semantic-dapp/components';
import type { SemanticBundle } from '@semantic-dapp/export';
import { AppProviders } from './wallet/Providers.js';
import { useContractRuntime } from './runtime.js';
import { loadBundle } from './bundle.js';

const CONTRACT_ID = 'contract';
const FALLBACK_RPC = 'http://127.0.0.1:8545';

/** A usable RPC URL: the bundle's, or a local default so the app never crashes. */
function effectiveRpc(bundle: SemanticBundle): string {
  return bundle.rpcUrl && bundle.rpcUrl.length > 0 ? bundle.rpcUrl : FALLBACK_RPC;
}

/** Inner view: has providers in scope, so it can use wagmi hooks. */
function BundleView({ bundle, isDemo }: { bundle: SemanticBundle; isDemo: boolean }) {
  // The bundle schema validates ABI shape but types inputs loosely; it is a real
  // ABI at runtime, so narrow it for viem/abitype consumers.
  const abi = bundle.abi as Abi;
  const model = useMemo(() => normalizeAbi(abi), [abi]);
  const runtime = useContractRuntime({
    abi,
    chainId: bundle.chainId,
    rpcUrl: effectiveRpc(bundle),
    ...(bundle.address ? { address: bundle.address } : {}),
    ...(bundle.contractName ? { name: bundle.contractName } : {}),
  });

  return (
    <div className="app-shell">
      <header className="app-header">
        <div>
          <h1 className="app-header__title">{bundle.contractName ?? bundle.name}</h1>
          <span className="app-header__sub">
            chain {bundle.chainId}
            {bundle.address ? ` · ${bundle.address}` : ''}
            {isDemo ? ' · demo bundle' : ''}
          </span>
        </div>
        <ConnectButton showBalance={false} chainStatus="icon" accountStatus="address" />
      </header>

      <GeneratedApp
        manifest={bundle.manifest}
        model={model}
        runtime={runtime}
        contractId={CONTRACT_ID}
        safety={bundle.address ? {} : undefined}
      />

      <footer className="app-footer">
        Generated by Semantic Dapp · runs entirely in your browser
      </footer>

      <ToastViewport />
    </div>
  );
}

export function App() {
  const [loaded, setLoaded] = useState<{ bundle: SemanticBundle; isDemo: boolean } | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadBundle()
      .then((result) => {
        if (!cancelled) setLoaded(result);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (error)
    return (
      <div className="app-shell">
        <p className="app-error">{error}</p>
      </div>
    );
  if (!loaded)
    return (
      <div className="app-shell">
        <p className="app-status">Loading…</p>
      </div>
    );

  return (
    <AppProviders
      key={`${loaded.bundle.chainId}:${effectiveRpc(loaded.bundle)}`}
      chainId={loaded.bundle.chainId}
      rpcUrl={effectiveRpc(loaded.bundle)}
      name={loaded.bundle.contractName ?? loaded.bundle.name}
    >
      <BundleView bundle={loaded.bundle} isDemo={loaded.isDemo} />
    </AppProviders>
  );
}
